"""tyre_degradation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wm2O_9Oi2LC0Iw7NKzw6Oyoi2q23r3wo

Isolates true tyre degradation from confounds (fuel load / session progress, traffic, track evolution,
driver/car pace) using only laps built from **causal, pre-lap-known or controlled-for** features.

**Target:** `LapTimeSeconds`
**No leakage:** every column that is mathematically derived from the same lap's timing (sector times,
speed traps, `IsPersonalBest`, the `_F1_V4` lap-time duplicates) is dropped. Track evolution and
"how fast is the field going right now" are rebuilt from scratch using `shift(1)` so the current lap's
own time is never used to predict itself.
**Validation:** `GroupKFold` grouped by **stint** (`Year+Event+Session+Driver+Stint`), so laps from the
same stint never leak across train/test — a random split would look great and be a lie.
"""


from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from scipy.stats import spearmanr
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor
import warnings
warnings.filterwarnings("ignore")

SEED = 42
np.random.seed(SEED)


BASE_DIR = Path(__file__).resolve().parent
CSV_PATH = BASE_DIR / "ENRICHED_TYRE_DATASET_2022_ONWARDS.csv"
df = pd.read_csv(CSV_PATH)
print(df.shape)
df.head()

df = df[df['ModelEligible'] == True].copy()

VALID_COMPOUNDS = ['SOFT', 'MEDIUM', 'HARD', 'INTERMEDIATE', 'WET']
df = df[df['Compound'].isin(VALID_COMPOUNDS)].copy()

REQUIRED = ['LapTimeSeconds', 'TyreAge', 'Compound', 'Team', 'Driver', 'Stint',
            'Year', 'Event', 'SessionName', 'LapNumber']
df = df.dropna(subset=REQUIRED).copy()
df = df[df['LapTimeSeconds'] > 0].copy()

df = df[df['YellowFlagAffected'] == False].copy()

df['SessionKey'] = (df['Year'].astype(str) + '_' + df['Event'].astype(str) + '_' +
                     df['SessionName'].astype(str))
df['StintKey'] = df['SessionKey'] + '_' + df['Driver'].astype(str) + '_' + df['Stint'].astype(str)

med = df.groupby('SessionKey')['LapTimeSeconds'].transform('median')
df = df[df['LapTimeSeconds'] <= med * 1.5].copy()

print("Rows after cleaning:", len(df), " | Stints:", df['StintKey'].nunique())

"""## 3. Leakage audit

Dropped entirely (same-lap outcome columns — using them would mean predicting the lap time
*with the lap time's own components*):

| Column | Why it's leakage |
|---|---|
| `LapTime`, `Sector1/2/3Time(+SessionTime)` | Sum ≈ the target itself |
| `SpeedI1/I2/FL/ST` | Speed traps recorded *during this exact lap* |
| `IsPersonalBest` | Near-tautological with a fast lap |
| `LapTimeSeconds_F1_V4` | Duplicate/rounded copy of the target |
| `SessionCommonMedianLapTime_V4`, `LapVsSessionCommonMode_V4` | Arithmetic derived from the target |
| Raw `Telemetry*` (non-`_V4`) | 100% null in this dataset (unusable) |
| `Telemetry*_V4` speed/throttle/RPM/gear stats | These describe how fast the car was driven **on this lap** — using them to predict this lap's time is circular |
| `PitInTime`/`PitOutTime`/`Position`/`Deleted*` | Fully null / not pre-lap info |

Kept as **confound-control features** (this is the whole point of the brief — isolate tyre wear
*from* these, don't discard them):
- **Fuel / session position:** `LapNumber`, `SessionProgress`
- **Traffic:** all `Traffic*_V4` gap/exposure columns
- **Track evolution:** rebuilt causally below (`SessionPaceEvolution`, `DriverBestSoFar`) using only
  laps seen *before* the current one (`shift(1)`) — the real column names in the CSV that summarize
  a whole session are excluded because they're computed over laps that include the current one.
- **Weather:** `AirTemp`, `TrackTemp`, `Humidity`, `Pressure`, `WindSpeed`, `Rainfall`
- **Car/driver pace baseline:** `Driver`, `Team` (categorical)
- **Track status:** `TrackStatusCode`

"""

df = df.sort_values(['SessionKey', 'Driver', 'LapNumber']).reset_index(drop=True)

df['SessionPaceEvolution'] = (
    df.groupby('SessionKey')['LapTimeSeconds']
      .transform(lambda s: s.shift(1).expanding().median())
)
df['DriverBestSoFar'] = (
    df.groupby(['SessionKey', 'Driver'])['LapTimeSeconds']
      .transform(lambda s: s.shift(1).expanding().min())
)

global_pace_fallback = df['LapTimeSeconds'].median()

df['SessionPaceEvolution'] = (
    df['SessionPaceEvolution']
    .fillna(global_pace_fallback)
)

df['DriverBestSoFar'] = (
    df['DriverBestSoFar']
    .fillna(global_pace_fallback)
)

df['TyreAge_sq'] = df['TyreAge'] ** 2
df['TyreAge_cb'] = df['TyreAge'] ** 3

gap_cols = ['TrafficGapMean_V4', 'TrafficGapMedian_V4', 'TrafficGapMin_V4', 'TrafficGapStd_V4']
for c in gap_cols:
    fill_val = df[c].max() * 2 if df[c].notnull().any() else 999.0
    df[c] = df[c].fillna(fill_val)

frac_cols = ['TrafficCloseFraction_V4', 'TrafficVeryCloseFraction_V4',
             'TrafficExposureScore_V4', 'TrafficDriverAheadFraction_V4']
for c in frac_cols:
    df[c] = df[c].fillna(0.0)

df['TrafficExposureLevel_V4'] = df['TrafficExposureLevel_V4'].fillna('NONE')

for c in ['FreshTyre', 'Rainfall']:
    df[c] = df[c].astype(float)

print("Feature engineering done.")

CAT_COLS = ['Driver', 'Team', 'Compound', 'Event', 'SessionName', 'TrafficExposureLevel_V4']
NUM_COLS = ['TyreAge', 'TyreAge_sq', 'TyreAge_cb', 'LapNumber', 'SessionProgress',
            'AirTemp', 'TrackTemp', 'Humidity', 'Pressure', 'WindSpeed', 'TrackStatusCode',
            'TrafficGapMean_V4', 'TrafficGapMedian_V4', 'TrafficGapMin_V4', 'TrafficGapStd_V4',
            'TrafficCloseFraction_V4', 'TrafficVeryCloseFraction_V4', 'TrafficExposureScore_V4',
            'TrafficDriverAheadFraction_V4', 'SessionPaceEvolution', 'DriverBestSoFar']
BOOL_COLS = ['FreshTyre', 'Rainfall']
FEATURES = CAT_COLS + NUM_COLS + BOOL_COLS

for c in CAT_COLS:
    df[c] = df[c].astype('category')

X = df[FEATURES].copy()
y = df['LapTimeSeconds'].values
groups = df['StintKey'].values

cat_idx = [X.columns.get_loc(c) for c in CAT_COLS]
print("Features:", len(FEATURES), "| Rows:", len(X))
assert X.isnull().sum().sum() == 0, "unexpected nulls left in feature matrix"

N_SPLITS = 5
gkf = GroupKFold(n_splits=N_SPLITS)

oof_lgb = np.zeros(len(X))
oof_xgb = np.zeros(len(X))
oof_cat = np.zeros(len(X))

lgb_models, xgb_models, cat_models = [], [], []

for fold, (tr_idx, te_idx) in enumerate(gkf.split(X, y, groups)):
    X_tr, X_te = X.iloc[tr_idx], X.iloc[te_idx]
    y_tr, y_te = y[tr_idx], y[te_idx]

    lgb_train = lgb.Dataset(X_tr, y_tr, categorical_feature=CAT_COLS, free_raw_data=False)
    lgb_valid = lgb.Dataset(X_te, y_te, categorical_feature=CAT_COLS, reference=lgb_train, free_raw_data=False)
    lgb_params = dict(objective='regression', metric='mae', learning_rate=0.03,
                       num_leaves=63, max_depth=8, min_data_in_leaf=20,
                       feature_fraction=0.85, bagging_fraction=0.85, bagging_freq=5,
                       lambda_l1=0.1, lambda_l2=0.5, seed=SEED, verbose=-1)
    m_lgb = lgb.train(lgb_params, lgb_train, num_boost_round=3000, valid_sets=[lgb_valid],
                       callbacks=[lgb.early_stopping(100, verbose=False)])
    oof_lgb[te_idx] = m_lgb.predict(X_te, num_iteration=m_lgb.best_iteration)
    lgb_models.append(m_lgb)

    X_tr_xgb = X_tr.copy(); X_te_xgb = X_te.copy()
    for c in CAT_COLS:
        X_tr_xgb[c] = X_tr_xgb[c].cat.codes
        X_te_xgb[c] = X_te_xgb[c].cat.codes
    dtrain = xgb.DMatrix(X_tr_xgb, label=y_tr)
    dvalid = xgb.DMatrix(X_te_xgb, label=y_te)
    xgb_params = dict(objective='reg:squarederror', eta=0.03, max_depth=8,
                       subsample=0.85, colsample_bytree=0.85, min_child_weight=5,
                       reg_alpha=0.1, reg_lambda=1.0, seed=SEED)
    m_xgb = xgb.train(xgb_params, dtrain, num_boost_round=3000,
                       evals=[(dvalid, 'valid')], early_stopping_rounds=100, verbose_eval=False)
    oof_xgb[te_idx] = m_xgb.predict(dvalid, iteration_range=(0, m_xgb.best_iteration + 1))
    xgb_models.append(m_xgb)

    m_cat = CatBoostRegressor(iterations=3000, learning_rate=0.03, depth=8,
                               l2_leaf_reg=3.0, loss_function='MAE', random_seed=SEED,
                               early_stopping_rounds=100, verbose=False)
    m_cat.fit(X_tr, y_tr, cat_features=cat_idx, eval_set=(X_te, y_te))
    oof_cat[te_idx] = m_cat.predict(X_te)
    cat_models.append(m_cat)

    print(f"Fold {fold} done.")

def metrics(y_true, y_pred, label):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = mean_squared_error(y_true, y_pred) ** 0.5
    r2 = r2_score(y_true, y_pred)
    sp = spearmanr(y_true, y_pred).correlation
    print(f"{label:22s} MAE={mae:6.3f}  RMSE={rmse:6.3f}  R2={r2:6.4f}  Spearman={sp:6.4f}")
    return mae, rmse, r2, sp

metrics(y, oof_lgb, "LightGBM")
metrics(y, oof_xgb, "XGBoost")
metrics(y, oof_cat, "CatBoost")

w = np.array([1/mean_absolute_error(y, oof_lgb),
              1/mean_absolute_error(y, oof_xgb),
              1/mean_absolute_error(y, oof_cat)])
w = w / w.sum()
oof_blend = w[0]*oof_lgb + w[1]*oof_xgb + w[2]*oof_cat
print("blend weights (lgb, xgb, cat):", np.round(w, 3))
wl, wx, wc = w
metrics(y, oof_blend, "ENSEMBLE (blend)")

fig, ax = plt.subplots(1, 2, figsize=(13, 5))
ax[0].scatter(y, oof_blend, s=4, alpha=0.3)
lims = [min(y.min(), oof_blend.min()), max(y.max(), oof_blend.max())]
ax[0].plot(lims, lims, 'r--', lw=1)
ax[0].set_xlabel("Actual LapTimeSeconds"); ax[0].set_ylabel("Predicted")
ax[0].set_title("OOF Predicted vs Actual (leak-free CV)")

resid = y - oof_blend
ax[1].hist(resid, bins=60)
ax[1].set_title(f"Residuals (mean={resid.mean():.3f}s, std={resid.std():.3f}s)")
plt.tight_layout(); plt.show()

"""## 9. Final production model
Refit each model family on **all** cleaned data (no holdout) for deployment / degradation-curve
extraction. Cross-validated metrics above are the honest generalization estimate — this step is
just "use every lap we have" for the model you'll actually ship.

"""

lgb_full = lgb.train(lgb_params, lgb.Dataset(X, y, categorical_feature=CAT_COLS),
                      num_boost_round=int(np.mean([m.best_iteration for m in lgb_models])))

X_xgb_full = X.copy()
for c in CAT_COLS:
    X_xgb_full[c] = X_xgb_full[c].cat.codes
xgb_full = xgb.train(xgb_params, xgb.DMatrix(X_xgb_full, label=y),
                      num_boost_round=int(np.mean([m.best_iteration for m in xgb_models])))

cat_full = CatBoostRegressor(iterations=int(np.mean([m.get_best_iteration() for m in cat_models])),
                              learning_rate=0.03, depth=8, l2_leaf_reg=3.0,
                              loss_function='MAE', random_seed=SEED, verbose=False)
cat_full.fit(X, y, cat_features=cat_idx)

print("Final models trained on", len(X), "laps.")

"""## 10. Clean tyre-degradation curves (the actual deliverable)
Partial-dependence style: hold every confound at its **typical, controlled** value (representative
fuel/session position, no traffic, average weather, median driver/team baseline) and sweep `TyreAge`
per compound. Because the confounds are pinned, the resulting curve is the model's isolated estimate
of pure tyre wear.

"""

def predict_blend(Xd):
    p_lgb = lgb_full.predict(Xd)
    Xd_xgb = Xd.copy()
    for c in CAT_COLS:
        Xd_xgb[c] = Xd_xgb[c].cat.codes
    p_xgb = xgb_full.predict(xgb.DMatrix(Xd_xgb))
    p_cat = cat_full.predict(Xd)
    return w[0]*p_lgb + w[1]*p_xgb + w[2]*p_cat

baseline = X.median(numeric_only=True)
mode_row = X[CAT_COLS].mode().iloc[0]

tyre_age_range = np.arange(1, 41)
plt.figure(figsize=(9, 6))
for compound in ['SOFT', 'MEDIUM', 'HARD']:
    rows = []
    for age in tyre_age_range:
        r = {c: baseline[c] for c in NUM_COLS}
        r.update({c: mode_row[c] for c in CAT_COLS})
        r.update({c: 0.0 for c in BOOL_COLS})
        r['Compound'] = compound
        r['TyreAge'] = age
        r['TyreAge_sq'] = age ** 2
        r['TyreAge_cb'] = age ** 3
        r['FreshTyre'] = 1.0
        rows.append(r)
    curve_df = pd.DataFrame(rows)[FEATURES]
    for c in CAT_COLS:
        curve_df[c] = curve_df[c].astype(X[c].dtype)
    preds = predict_blend(curve_df)
    plt.plot(tyre_age_range, preds, marker='o', ms=3, label=compound)

plt.xlabel("Tyre Age (laps)"); plt.ylabel("Predicted clean lap time (s)")
plt.title("Isolated tyre-degradation curve (confounds held constant)")
plt.legend(); plt.grid(alpha=0.3); plt.show()

imp = pd.Series(lgb_full.feature_importance(importance_type='gain'), index=FEATURES)
imp = imp.sort_values(ascending=False)
imp.head(15).plot(kind='barh', figsize=(7,5)); plt.gca().invert_yaxis()
plt.title("LightGBM feature importance (gain)"); plt.tight_layout(); plt.show()
imp.head(15)

"""## 12. Race-day validation hook
This dataset is Practice 1/2/3 only (no `Race` rows), so the "predicted wear vs actual race pace"
comparison from the brief needs a Race-session extract added later. Drop it in and run this cell —
everything upstream (feature engineering, leakage exclusions) is written generically so it applies
unchanged to Race rows too.

"""

print("Add a Race-session CSV and re-run this cell to validate against real race-day pace.")


import numpy as np
import pandas as pd

compounds = ['SOFT', 'MEDIUM', 'HARD']
tyre_age_range = np.arange(2, 39)


reference = X.iloc[[0]].copy()

for c in NUM_COLS:
    if c in X.columns:
        reference[c] = X[c].median()

for c in CAT_COLS:
    if c in X.columns:
        reference[c] = X[c].mode(dropna=True).iloc[0]

for c in BOOL_COLS:
    if c in X.columns:
        reference[c] = 0.0



def predict_blend_10b_final(Xd):

    p_lgb = lgb_full.predict(Xd)

    Xd_xgb = Xd.copy()

    for c in CAT_COLS:
        Xd_xgb[c] = Xd_xgb[c].astype('category').cat.codes

    p_xgb = xgb_full.predict(
        xgb.DMatrix(Xd_xgb)
    )

    p_cat = cat_full.predict(Xd)

    return (
        w[0] * p_lgb +
        w[1] * p_xgb +
        w[2] * p_cat
    )



results = []

for compound in compounds:

    rows = []

    for age in tyre_age_range:

        r = reference.copy()

        r['Compound'] = compound
        r['TyreAge'] = float(age)
        r['TyreAge_sq'] = float(age ** 2)
        r['TyreAge_cb'] = float(age ** 3)

        r['FreshTyre'] = (
            1.0 if age == tyre_age_range[0] else 0.0
        )

        rows.append(r)

    curve_df = pd.concat(
        rows,
        ignore_index=True
    )

    curve_df = curve_df[FEATURES].copy()


    for c in CAT_COLS:
        curve_df[c] = curve_df[c].astype(str)

    for c in CAT_COLS:
        values = list(
            pd.Series(
                list(X[c].dropna().unique()) +
                list(curve_df[c].dropna().unique())
            ).astype(str).unique()
        )

        curve_df[c] = pd.Categorical(
            curve_df[c],
            categories=values
        )


    preds = predict_blend_10b_final(curve_df)


    per_lap = np.diff(preds)

    avg_deg = np.mean(per_lap)

    linear_deg = np.polyfit(
        tyre_age_range,
        preds,
        1
    )[0]

    total_deg = preds[-1] - preds[0]

    results.append({
        'Compound': compound,
        'Average degradation (s/lap)': avg_deg,
        'Linear degradation (s/lap)': linear_deg,
        'Lap 2 predicted time (s)': preds[0],
        'Lap 38 predicted time (s)': preds[-1],
        'Total degradation (s)': total_deg
    })



deg_df_10b_final = pd.DataFrame(results)

print("\n" + "=" * 80)
print("10B — FINAL CONTROLLED ML TYRE DEGRADATION")
print("=" * 80)

print(
    deg_df_10b_final.to_string(
        index=False,
        float_format=lambda x: f"{x:.5f}"
    )
)


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

compounds = ['SOFT', 'MEDIUM', 'HARD']


print("TyreAge in FEATURES:", 'TyreAge' in FEATURES)
print("TyreAge_sq in FEATURES:", 'TyreAge_sq' in FEATURES)
print("TyreAge_cb in FEATURES:", 'TyreAge_cb' in FEATURES)
print("Compound in FEATURES:", 'Compound' in FEATURES)

if 'TyreAge' not in FEATURES:
    raise ValueError(
        "TyreAge is missing from FEATURES. "
        "Current FEATURES = " + str(FEATURES)
    )


age_min = max(2, int(df['TyreAge'].min()))
age_max = min(38, int(df['TyreAge'].max()))

tyre_age_range = np.arange(age_min, age_max + 1)

print(f"\nUsing tyre ages: {age_min} → {age_max}")



reference = X.iloc[[0]].copy()

for c in NUM_COLS:
    if c in X.columns:
        reference[c] = X[c].median()

for c in CAT_COLS:
    if c in X.columns:
        reference[c] = X[c].mode(dropna=True).iloc[0]

for c in BOOL_COLS:
    if c in X.columns:
        reference[c] = 0.0



def predict_blend_clean(Xd):

    p_lgb = lgb_full.predict(Xd)

    Xd_xgb = Xd.copy()

    for c in CAT_COLS:
        Xd_xgb[c] = Xd_xgb[c].astype('category').cat.codes

    p_xgb = xgb_full.predict(
        xgb.DMatrix(Xd_xgb)
    )

    p_cat = cat_full.predict(Xd)

    return (
        w[0] * p_lgb +
        w[1] * p_xgb +
        w[2] * p_cat
    )



all_curves = {}
results = []

for compound in compounds:

    rows = []

    for age in tyre_age_range:

        r = reference.copy()

        r['Compound'] = compound
        r['TyreAge'] = float(age)

        if 'TyreAge_sq' in FEATURES:
            r['TyreAge_sq'] = float(age ** 2)

        if 'TyreAge_cb' in FEATURES:
            r['TyreAge_cb'] = float(age ** 3)

        if 'FreshTyre' in FEATURES:
            r['FreshTyre'] = (
                1.0 if age == age_min else 0.0
            )

        rows.append(r)

    curve_df = pd.concat(
        rows,
        ignore_index=True
    )

    curve_df = curve_df[FEATURES].copy()


    for c in CAT_COLS:
        if c in curve_df.columns:
            curve_df[c] = curve_df[c].astype('category')


    preds = predict_blend_clean(curve_df)

    all_curves[compound] = preds


    per_lap = np.diff(preds)

    avg_deg = np.mean(per_lap)

    linear_deg = np.polyfit(
        tyre_age_range,
        preds,
        1
    )[0]

    total_deg = preds[-1] - preds[0]

    results.append({
        'Compound': compound,
        'Average degradation (s/lap)': avg_deg,
        'Linear degradation (s/lap)': linear_deg,
        f'Lap {age_min} predicted time (s)': preds[0],
        f'Lap {age_max} predicted time (s)': preds[-1],
        'Total degradation (s)': total_deg
    })



deg_df_clean = pd.DataFrame(results)

print("\n" + "=" * 80)
print("CONTROLLED ML TYRE DEGRADATION RESULTS")
print("=" * 80)

print(
    deg_df_clean.to_string(
        index=False,
        float_format=lambda x: f"{x:.5f}"
    )
)



plt.figure(figsize=(10, 6))

for compound in compounds:

    plt.plot(
        tyre_age_range,
        all_curves[compound],
        marker='o',
        markersize=3,
        label=compound
    )

plt.xlabel("Tyre Age (laps)")
plt.ylabel("Predicted Clean Lap Time (s)")
plt.title(
    "Controlled ML Tyre-Degradation Curves\n"
    "Confounding Variables Held Constant"
)

plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


import numpy as np
import pandas as pd
import xgboost as xgb


print("=" * 95)
print("CONTROLLED ML TYRE DEGRADATION CURVE")
print("=" * 95)



base = df.copy()

base["Compound"] = (
    base["Compound"]
    .astype(str)
    .str.upper()
)


base = base[
    base["Compound"].isin(
        ["SOFT", "MEDIUM", "HARD"]
    )
].copy()


base = base[
    base["LapTimeSeconds"].notna()
].copy()


if "ModelEligible" in base.columns:

    base = base[
        base["ModelEligible"]
        .fillna(False)
        .astype(bool)
    ].copy()


if "NonRepresentative" in base.columns:

    base = base[
        ~base["NonRepresentative"]
        .fillna(False)
        .astype(bool)
    ].copy()


print(
    f"Eligible real laps: {len(base):,}"
)



def most_common(series):

    s = series.dropna()

    if len(s) == 0:
        return None

    return s.mode().iloc[0]


def median_numeric(series):

    s = pd.to_numeric(
        series,
        errors="coerce"
    ).dropna()

    if len(s) == 0:
        return 0.0

    return float(
        s.median()
    )



def build_reference(compound):

    c = base[
        base["Compound"] == compound
    ].copy()


    X = pd.DataFrame(
        index=[0],
        columns=FEATURES
    )


    for feature in FEATURES:


        if feature in CAT_COLS:

            value = most_common(
                c[feature]
            )

            X.loc[0, feature] = value


        else:

            X.loc[0, feature] = median_numeric(
                c[feature]
            )



    if "Compound" in X.columns:

        X.loc[0, "Compound"] = compound


    return X



def prepare_lgb(X):

    X = X.copy()

    booster = lgb_full

    feature_names = booster.feature_name()

    pandas_categories = getattr(
        booster,
        "pandas_categorical",
        []
    )


    lgb_cat_cols = [
        c for c in FEATURES
        if c in CAT_COLS
        and c in feature_names
    ]


    if (
        len(pandas_categories) ==
        len(lgb_cat_cols)
    ):

        for c, cats in zip(
            lgb_cat_cols,
            pandas_categories
        ):

            X[c] = pd.Categorical(
                X[c],
                categories=cats
            )

    else:

        for c in lgb_cat_cols:

            cats = (
                pd.Series(
                    df[c]
                )
                .astype("category")
                .cat.categories
            )

            X[c] = pd.Categorical(
                X[c],
                categories=cats
            )


    for c in X.columns:

        if c not in lgb_cat_cols:

            X[c] = pd.to_numeric(
                X[c],
                errors="coerce"
            )


    return X



def prepare_xgb(X):

    X = X.copy()


    for c in CAT_COLS:

        if c in X.columns:

            cats = (
                pd.Series(
                    df[c]
                )
                .astype("category")
                .cat.categories
            )

            X[c] = pd.Categorical(
                X[c],
                categories=cats
            ).codes


    for c in X.columns:

        X[c] = pd.to_numeric(
            X[c],
            errors="coerce"
        )


    return X



def prepare_cat(X):

    X = X.copy()


    cat_indices = (
        cat_full
        .get_cat_feature_indices()
    )


    feature_names = list(
        cat_full.feature_names_
    )


    cat_names = [
        feature_names[i]
        for i in cat_indices
        if i < len(feature_names)
    ]


    for c in cat_names:

        if c in X.columns:

            X[c] = (
                X[c]
                .astype("object")
                .where(
                    X[c].notna(),
                    "MISSING"
                )
                .astype(str)
            )


    for c in X.columns:

        if c not in cat_names:

            X[c] = pd.to_numeric(
                X[c],
                errors="coerce"
            )


    return X



def predict_all(X):

    Xl = prepare_lgb(X)

    pred_lgb = float(
        lgb_full.predict(Xl)[0]
    )


    Xx = prepare_xgb(X)

    dm = xgb.DMatrix(
        Xx,
        feature_names=list(
            Xx.columns
        )
    )

    pred_xgb = float(
        xgb_full.predict(dm)[0]
    )


    Xc = prepare_cat(X)

    pred_cat = float(
        cat_full.predict(Xc)[0]
    )


    return (
        pred_lgb,
        pred_xgb,
        pred_cat
    )



age_max = int(
    base["TyreAge"]
    .dropna()
    .max()
)

age_max = min(
    age_max,
    40
)


age_min = max(
    1,
    int(
        base["TyreAge"]
        .dropna()
        .min()
    )
)


print(
    f"\nReal observed tyre-age range: "
    f"{age_min} → {age_max}"
)



all_rows = []


for compound in [
    "SOFT",
    "MEDIUM",
    "HARD"
]:

    print(
        f"\nProcessing {compound}..."
    )


    reference = build_reference(
        compound
    )


    rows = []


    for age in range(
        age_min,
        age_max + 1
    ):

        X = reference.copy()



        if "TyreAge" in X.columns:

            X.loc[0, "TyreAge"] = age


        if "TyreAgeSq" in X.columns:

            X.loc[0, "TyreAgeSq"] = (
                age ** 2
            )


        if "TyreAge²" in X.columns:

            X.loc[0, "TyreAge²"] = (
                age ** 2
            )


        if "TyreAgeCubed" in X.columns:

            X.loc[0, "TyreAgeCubed"] = (
                age ** 3
            )


        if "TyreAge³" in X.columns:

            X.loc[0, "TyreAge³"] = (
                age ** 3
            )


        if "FreshTyre" in X.columns:

            X.loc[0, "FreshTyre"] = (
                age == 1
            )



        pl, px, pc = predict_all(
            X
        )


        rows.append({

            "Compound":
                compound,

            "TyreAge":
                age,

            "LightGBM_s":
                pl,

            "XGBoost_s":
                px,

            "CatBoost_s":
                pc
        })


    ccurve = pd.DataFrame(
        rows
    )



    for model in [
        "LightGBM_s",
        "XGBoost_s",
        "CatBoost_s"
    ]:

        ccurve[
            model.replace(
                "_s",
                "_Degradation_s"
            )
        ] = (
            ccurve[model] -
            ccurve[model].iloc[0]
        )



    ccurve[
        "Ensemble_s"
    ] = (
        wl * ccurve["LightGBM_s"] +
        wx * ccurve["XGBoost_s"] +
        wc * ccurve["CatBoost_s"]
    )


    ccurve[
        "Ensemble_Degradation_s"
    ] = (
        ccurve["Ensemble_s"] -
        ccurve["Ensemble_s"].iloc[0]
    )


    all_rows.append(
        ccurve
    )


controlled_curve = pd.concat(
    all_rows,
    ignore_index=True
)



summary_rows = []


for compound, c in controlled_curve.groupby(
    "Compound"
):

    c = c.sort_values(
        "TyreAge"
    ).copy()


    x = c[
        "TyreAge"
    ].values.astype(float)


    result = {
        "Compound":
            compound
    }


    for model in [
        "LightGBM",
        "XGBoost",
        "CatBoost",
        "Ensemble"
    ]:

        y = c[
            model + "_Degradation_s"
        ].values.astype(float)


        slope = np.polyfit(
            x,
            y,
            1
        )[0]


        total = (
            y[-1] -
            y[0]
        )


        average = (
            total /
            (x[-1] - x[0])
        )


        result[
            model +
            "_linear_s_per_lap"
        ] = slope


        result[
            model +
            "_average_s_per_lap"
        ] = average


        result[
            model +
            "_total_loss_s"
        ] = total


    summary_rows.append(
        result
    )


controlled_summary = pd.DataFrame(
    summary_rows
)



print("\n")
print("=" * 95)
print("🔥 CONTROLLED ML DEGRADATION RESULTS")
print("=" * 95)

print(controlled_summary.round(5).to_string(index=False))



print("\n")
print("=" * 95)
print("MODEL-DERIVED s/LAP")
print("=" * 95)


for _, row in controlled_summary.iterrows():

    print(
        f"\n{row['Compound']}"
    )

    print(
        f"  LightGBM : "
        f"{row['LightGBM_linear_s_per_lap']:.5f} s/lap"
    )

    print(
        f"  XGBoost  : "
        f"{row['XGBoost_linear_s_per_lap']:.5f} s/lap"
    )

    print(
        f"  CatBoost : "
        f"{row['CatBoost_linear_s_per_lap']:.5f} s/lap"
    )

    print(
        f"  Ensemble : "
        f"{row['Ensemble_linear_s_per_lap']:.5f} s/lap"
    )



controlled_summary.to_csv(
    "NEW_CONTROLLED_ML_DEGRADATION_RATES.csv",
    index=False
)

controlled_curve.to_csv(
    "NEW_CONTROLLED_ML_DEGRADATION_CURVES.csv",
    index=False
)


print("\n")
print("=" * 95)
print("✓ NEW FILES CREATED")
print("=" * 95)

print(
    "NEW_CONTROLLED_ML_DEGRADATION_RATES.csv"
)

print(
    "NEW_CONTROLLED_ML_DEGRADATION_CURVES.csv"
)

print(
    "\n✓ Existing models and datasets were NOT modified."
)
